name: Build All Filters

on:
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  build all:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node@18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      - name: Lint code
        # TODO: add a separate workflow for linting
        run: yarn lint

      - name: Build filters and patches
        run: TLS=insecure yarn build

      - name: Build patches
        run: yarn build:patches

      - name: Validate platforms and locales
        run: |
          yarn validate:platforms
          yarn validate:locales

      - name: Push to master
        run: yarn publish
