name: Build AdGuard filters

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 */1 * * *'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node@18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      - name: Build filters and update in repo
        run: |
          git config --global user.email "filters@adguard.com"
          git config --global user.name "Filters Builder"
          TLS=insecure yarn auto-build --mode ours

